name: Verify generation

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
      - develop

jobs:
  build:
    name: Verify generation
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17
        id: go

      - name: Check out code
        uses: actions/checkout@v2

      - name: Install protoc
        run: sudo apt install -y protobuf-compiler

      - name: Install dependencies
        run: sh ./script/gettools.sh

      - name: Generate
        run: make all

      - name: Verify missed generation
        run: |
          diff=$(git status --porcelain=v1 2>/dev/null | wc -l | xargs)
          if [ $diff -ne 0 ]; then
            echo "Some files were not generated."
            exit 1
          fi
